### ISSUE TITLE
Everdrive 64 Compatibility

### ISSUE THREAD

**Issue by Kuuyashii** [Brotenko/PMMasterQuest#11]
I can't seem to get the rom to run on my Everdrive 64. I looked around online and I think someone mentioned that there's a compatibility issue somewhere. Does this mean there is no way to play this ROM on my Everdrive or is there a work around? Are there other methods of patching the game to make it compatible perhaps?

**Comment by jdfr228** [comment]
Just in case this is helpful, I joined the Discord a while back and asked about this for a different flash cart and the developers indicated that the current version is NOT console compatible, but they planned to make it so in the next release.  However, it's of course been quite a while since there was any public news about the next version, so I don't know if it still has active developers or not.
