### ISSUE TITLE
Readme missing info?

### ISSUE THREAD

**Issue by preston-wagner** [Brotenko/PMMasterQuest#14]
Hey, in the readme, it says to address the audio stuttering you should "change the FB (Framebuffer) settings to the same as the picture below", but there is no picture. What are the correct settings?

**Comment by Brotenko** [comment]
We 1-to-1 copied that part of the readme from the FAQ channel on the Discord. Since this project is effectively depricated from my point of view (Another community member is currently working on a 2.0 version), I do not intent to update the readme anymore - There are several of these small issues in there. 

Sorry for the inconvenience, but at some point I sadly have to draw a line. I hope you enjoy the game anyway and for further help feel free to join the Discord, the active community on there is very helpful with these things.
